menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}
- {name: 'ARCHIVES', url: '/archives'}
- {name: 'CONTACT', url: '/contact'}

archives:
- {name: 'Mathematics', url: 'mathematics'}
- {name: 'Classical Mechanics', url: 'classical-mechanics'}
- {name: 'Electromagnetism', url: 'electromagnetism'}
- {name: 'Quamtum Mechanics', url: 'quantum-mechanics'}
- {name: 'Relativity', url: 'relativity'}
- {name: 'Problems', url: 'problems'}
- {name: 'PNS Lecture Notes', url: 'pns-lecture-notes'}

social:
- {icon: 'google', link: 'mailto:yoonmyeong673@gmail.com'}
- {icon: 'instagram', link: 'https://www.instagram.com/ym._.673/'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0003-0959-2113'}

contacts:
- {name: 'Myeong Yoon', title: 'Student', interests: 'Theoretical Physics', school: 'Gyeonggi Science High School for the Gifted', number: '40th', phone: '+82 (0)10 3016 7688', email: 'yoonmyeong673@gmail.com'}
